[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E222A"
textColor = "#FAFAFA"
font = "sans serif"
